version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"