version: '3'

services:
  example:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    user: "1000:1000"
    command: ["dotnet", "run"]