version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - djangonetwork
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/static
    environment:
      - DJANGO_DEBUG=False
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    user: "1000:1000"
    links:
      - db:db
    restart: always
    networks:
      - djangonetwork
    depends_on:
      - db

networks:
  djangonetwork:
    driver: bridge