version: '3'

networks:
  employee_management_network:
    name: employee_management_network
    driver: bridge

services:
  database:
    image: mysql:5.7
    container_name: database
    restart: on-failure
    privileged: true
    environment:
      - MYSQL_DATABASE=employee_management_system
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - employee_management_network

  springboot-backend:
    image: springboot-backend
    container_name: springboot-backend
    restart: on-failure
    build:
      context: ./springboot-backend/
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
    networks:
      - employee_management_network
    
  react-frontend:
    image: react-frontend
    container_name: react-frontend
    restart: on-failure
    build: 
      context: ./react-frontend/
      dockerfile: Dockerfile
    networks:
      - employee_management_network

  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    depends_on:
      - react-frontend
      - springboot-backend
    networks:
      - employee_management_network